### PR TITLE
Fixing two library incompatibility issues

### LINKED ISSUE #27: Plot not rendering in Add-on mode and strange rendering of Plot Curve Variables Selector
See attached image

image

### PR DESCRIPTION
**Pull request by ehsanshahidi**
This PR fixes:
- #27, 
- Unreported issue with signal push caused by use of deprecated `pandas.append`

The plot rendering issues is caused by [bqplot](https://github.com/bqplot/bqplot) incompatibility with `ipywidgets > 8.0.0` which is mentioned in `bqplot` documentation. Downgrading `ipywidgets` in data-lab causes other issues related to incompatibility of `viola` with older versions of `ipywidgets`. `plotly` was considered but @monstrorivas advised me of the lengthly `pip install` of it, so I went with `matplotlib` given there is no need for interactivity with the plot in this add-on.

The rendering issue with formulas seem to be related to `ipyvuetify.HtmlMath` which is `ipyvuetify`'s implementation of `MathJax`. I removed the usages of `HtmlMath` and instead added a script to the Vue template to call `MathJax`.

`pandas.append` is replaced with `concat`

I also added an option to `addon.json` to make python 3.11 default, and modified the add-on notebook to use a 3.11 kernel. There seems to be an issue where add-on manager still `pip install`s the requirements in 3.8. I am getting help to have this investigated. As such, this can get uploaded to jfrog when the issue is resolved or there is a workaround.

Testing:
To test, run `python package.py`, upload the resulting `.addon` file on Add-on Manager to install the add-on. You may have to manually update the kernel name in installation setting via Add-on Manager to ensure requirements are installed in python 3.11. This is a known Add-on Manager issue and will be fixed soon:
image

Upload an example csv file like the following to test plot curve.
[Book1.csv](https://github.com/user-attachments/files/17467914/Book1.csv)

### CODE REVIEW

**Comment by ehsanshahidi** [comment]
@monstrorivas Do you mind primary reviewing this?

**Comment by spokeydokeys** [comment]
Testing notes:
:white_check_mark: building wheel file with 3.11
:white_check_mark: building addon package 3.11
:white_check_mark: installing addon
:white_check_mark: opening addon from a workbench

I think it installed it using python 3.8.  I went to the data lab project and when I ran the notebook it selected the 3.8 kernel.  When I switched it to 3.11 and ran the cell, I got 
```
ModuleNotFoundError: No module named 'seeq.addons'

Error found at line 4 in cell 4.
```
Switching back to 3.8 let it run successfully

:white_check_mark: loading data
:x: displaying the data

I loaded in 
```
Curve,Flow,Head
Units,m^3/hr,m
Pump Curve 1,500,300
Pump Curve 1,750,290
Pump Curve 1,1000,250
```
It successfully loaded the data, but there it did not show it on the plot and some of the UI elements had funny little scroll bars... 

image

:white_check_mark: After some trials with units and numbers of points for my selected fit, I got it to push a result back to Seeq.

**Comment by spokeydokeys** [comment]
> I think it installed it using python 3.8. I went to the data lab project and when I opened the notebook it automatically selected the 3.8 kernel. When I switched it to 3.11 and ran the cell, I got
> 
> ```
> ModuleNotFoundError: No module named 'seeq.addons'
> 
> Error found at line 4 in cell 4.
> ```

I saw the note in `https://github.com/seeq12/seeq-udf-ui/pull/17` and tried checked what was in the python version field for this one and it was 38.  Uninstalling and reinstalling with 311 in the config fixed the issue and the appropriate libraries were installed in the python 3.11 kernel, however, the addon failed to load as it looks like it was launching with the 38 kernel from the Add-ons toolbar.

**Review by spokeydokeys — APPROVED** [review]

**Comment by ehsanshahidi** [comment]
> Testing notes: ✅ building wheel file with 3.11 ✅ building addon package 3.11 ✅ installing addon ✅ opening addon from a workbench 
> ✅ loading data 
> ✅ displaying the data. Looks good. 
> ✅ After some trials with units and numbers of points for my selected fit, I got it to push a result back to Seeq.

Thank you!

**Pull request merged**
